#!/bin/bash
 
PERSON1=dhanu
PERSON2=gopi

echo "$PERSON1:: hello $PERSON2. how are you"
echo "$PERSON2:: hi $PERSON1.iam good wt about you"
echo "$PERSON1:: iam learning devops my own $PERSON2"
echo "$PERSON2::oh its great $PERSON1 keep it up"
