# - name: ping the server
#   hosts: web #which hosts your ansible server conects
#   tasks: #list of tasks/modules/collections
#   -name: ping the server
#   ansible.builtin.ping: 


---
- name: Ping the server
  hosts: web  # This should match a group in your inventory
  gather_facts: false

  tasks:
    - name: Ping the server
      ansible.builtin.ping:
